import './globals.css'
import Navbar from './nav/Navbar'
import ToasterProvider from './providers/ToasterProvider'


export const metadata = {
  title: 'Auction App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ToasterProvider/>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  )
}
